"""change

Revision ID: 6b5b5e3d77b5
Revises: 46c4204de3f9
Create Date: 2026-09-13 12:31:41.797383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5b5e3d77b5'
down_revision: Union[str, Sequence[str], None] = '46c4204de3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_column('carrinho_itens', 'preco')
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('produtos_empresa_id_fkey'), 'produtos', type_='foreignkey')
    op.create_foreign_key(None, 'produtos', 'categorias', ['categoria_id'], ['id'])
    op.drop_column('produtos', 'empresa_id')
    op.create_unique_constraint('uq_email', 'usuarios', ['email'])


    # ### end Alembic commands ###




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email', 'usuarios', type_='unique')
    op.add_column('produtos', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.create_foreign_key(op.f('produtos_empresa_id_fkey'), 'produtos', 'empresas', ['empresa_id'], ['id'])
    op.drop_column('produtos', 'categoria_id')
    op.add_column('carrinho_itens', sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_table('categorias')

    # ### end Alembic commands ###
