"""Criando ck nome e empresa_id em filiais

Revision ID: 706f19d8ce13
Revises: 7e8ffbd702cd
Create Date: 2026-08-01 11:04:54.912168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706f19d8ce13'
down_revision: Union[str, Sequence[str], None] = '7e8ffbd702cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ck_unique_filial_id_empresa', 'filiais', ['empresa_id', 'nome'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_unique_filial_id_empresa', 'filiais', type_='unique')
    # ### end Alembic commands ###
