"""change

Revision ID: 85943b1cc1f9
Revises: f2e8b70012ce
Create Date: 2026-09-13 12:43:49.936663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85943b1cc1f9'
down_revision: Union[str, Sequence[str], None] = 'f2e8b70012ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.alter_column(
        'produtos',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )

    op.alter_column(
        'carrinho',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )    

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    
    op.alter_column(
        'produtos',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )

    op.alter_column(
        'carrinho',
        'created_at',
        existing_type=sa.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
