"""Nullable == True em Filiais.id na tabela Usuarios

Revision ID: f2d1736301ae
Revises: 706f19d8ce13
Create Date: 2026-08-07 13:38:12.802452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d1736301ae'
down_revision: Union[str, Sequence[str], None] = '706f19d8ce13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'filial_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'filial_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
